# Usuarios y roles
users:
  - username: "admin"
    password: "adminpass"   # En producción, usa env vars y hash
    role: "admin"
  - username: "op1"
    password: ""             # Sin password para operadores locales
    role: "operator"

# Residencias (clientes)
residences:
  - id: "resA"
    name: "Residencial Avenida Sur"
    url_base: "http://192.168.0.100:80"
    type: "html"
    relays:
      - id: 7
        name: "PuertaPrinc"
        cmd_template: "?relay={relay_id};st={state}"
      - id: 1
        name: "LuzPatio"
        cmd_template: "?relay={relay_id};st={state}"
  # ... hasta 50 entradas posibles

durations:
  - 2     # 2 segundos
  - 15    # 15 segundos
  - 0     # indefinido